# Original Git-wiki configurations
git_branch: "master"
wiki_folder: "wiki"

#
# Jekyll configurations
#

# You can customize it changing default layout for all pages
# More info: https://jekyllrb.com/docs/configuration/
#
# git-wiki includes some internal themes that you can choose
# check _layouts folder
#
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
 -
    scope:
      path: "wiki"
    values:
      permalink: /:basename
 -
    scope:
      path: "wiki_translations"
    values:
      permalink: /:basename
 -
    scope:
      path: "wiki_untranslated"
    values:
      permalink: /:basename
 -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "stk-wiki"

sass:
    style: compressed
plugins:
  - jekyll-redirect-from
  - jekyll_picture_tag

# This file will be written everytime page updated
exclude:
  - _translations/stk-website.pot

stk_version: "1.4"
stk_rc: "1.5-beta1"

# Disable Jekyll Picture Tag warnings when base image is smaller
picture:
  suppress_warnings: true
